owner: scratchstatus
repo: backend

# Add your sites here
sites:
  - name: Scratch - site-api
    url: https://scratch.mit.edu/site-api
    expectedStatusCodes:
      - 403
      - 404    
  - name: Scratch - API
    url: https://api.scratch.mit.edu
  - name: Scratch - CDN
    url: https://cdn.scratch.mit.edu/
    expectedStatusCodes:
      - 403
      - 404
  - name: Scratch - CDN2
    url: https://cdn2.scratch.mit.edu/
    expectedStatusCodes:
      - 403
      - 404
  - name: Scratch - Projects
    url: https://projects.scratch.mit.edu/

status-website:
  baseUrl: /backend
  logoUrl: https://scratchstatus.github.io/assets/upptime-icon.svg
  name: Scratch Status
  introTitle: "Scratch Status"
  introMessage: Use this site to see if scratch is down. Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See [scratch.mit.edu](https://scratch.mit.edu). ScratchStatus is not affilated in any way with Scratch. Ask 9gr on Scratch for help.
  navbar:
    - title: Backend
      href: /backend
    - title: Frontend
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customBodyHtml: "<iframe src='/assets/topbar.html' height='65px' width='100%' style='border-width:0; overflow:hidden;'></iframe>"
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org) and created for use for everybody at [Scratch](https://scratch.mit.edu). If you want to help improve this, comment on [my profile](https://scratch.mit.edu/users/9gr)
